<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>rocket.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="rocket.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.47.0" />
    <PackageReference Include="System.Management" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoogleServiceLib\GoogleServiceLib.csproj" />
  </ItemGroup>

</Project>